__author__ = 'Danny'
# Options and various game constants

SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50
HEAL_AMOUNT = 5
MAP_WIDTH = 80
MAP_HEIGHT = 43

BAR_WIDTH = 20
PANEL_HEIGHT = 7
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT

INVENTORY_WIDTH = 50

MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

ROOM_MAX_SIZE = 15
ROOM_MIN_SIZE = 6
MAX_ROOMS = 30

MAX_ROOM_MONSTERS = 3
MAX_ROOM_ITEMS = 2

# Field of view stuff
FOV_ALGO = 1
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 6

LIMIT_FPS = 20  #20 frames-per-second maximum